Repository samply/share-client, pull requests merged in 2021-05, with the labels that each got.

#31 Rename future builds from samply-* to gbn-*
  .github/workflows/ci-c4.yml
  .github/workflows/ci-dktk.yml
  .github/workflows/ci.yml
  pom.xml
Labels: enhancement

#32 Ensure that the dockerimage uses log4j configuration from src/docker/
  Dockerfile
Labels: bug

#39 Update Postgres to v4.2.20
  pom.xml
Labels: dependencies

#48 Fix Log4J Pattern
  src/docker/log4j2.xml
Labels: bug
